### ISSUE TITLE
Memory usage seems inaccurate on macOS

### ISSUE THREAD

**Issue by bfontaine** [nikopol/hi#1]
👋 

I get the following on my Mac:
```
mem    : ◼◼◼◼◼◼◼◼◼◻ 8156mo used / 8192mo
```

`htop` says only 4GB is currently used and the Activity Monitor says 6.6GB:
![](https://user-images.githubusercontent.com/1334295/46981090-15609f80-d0d7-11e8-9648-3690eba4dc54.png)

I’m not sure who’s right and what’s the better way to get that number.

**Comment by nikopol** [comment]
seems like `hi` includes the file cache. i'll investigate

**Comment by nikopol** [comment]
i've pushed a version (0.5) where i consider as "used memory" only "active page". is it ok for you @bfontaine ?

**Comment by bfontaine** [comment]
I tried the latest master:
```bash
curl -sL 'https://raw.githubusercontent.com/nikopol/hi/master/hi' | perl
```

```
mem    : ◼◼◼◻◻◻◻◻◻◻ 2494mo used / 8192mo
```

`htop` says "4.21G" and Activity Monitor ~5.6GB:
![](https://user-images.githubusercontent.com/1334295/59886011-a94cde80-93bd-11e9-8618-8491963d72c9.png)

:/

**Comment by nikopol** [comment]
ok, i've put used =  active + wired (application + residente).
thanks for your returns :+1:
